services:
  - type: web
    name: diabetes-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    workingDir: backend
    region: oregon
    plan: free
